title: Trevor's CSA Blog
description: A blog page for all of my activity in AP Computer Science A. I will regularly update this page with my progress and struggles throughout the course.
owner_name: Trevor Huang
github_username: trevorhuang1
github_repo: "csa_blog" 
baseurl: "/csa_blog"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" } 
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/blog.md
  - navigation/search.md
  - navigation/about.md
  - navigation/csa.md
  - README4YML.md
